#!/usr/bin/env python3
"""Generate Plater config file(s) from a directory of STL parts.

Given a directory, this scans it for parts and writes a `plater.conf` that
lists each part with its quantity. Two naming rules are honored:

  * Files whose name starts with "[a]" are treated as "Accent Parts" and are
    written to a separate config file instead of the main one.
  * Files whose base name (before the extension) ends with "_x<N>" are included
    <N> times, e.g. "bracket_x4.stl" -> quantity 4. Everything else gets 1.

Paths written into the config are relative to the config file, so the config is
written *inside* the target directory and references parts by their base name
(see https://github.com/RobotsWar/Plater -- "The plater.conf file").
"""
import argparse
import os
import re
import sys

# Matches a trailing "_x<number>" on the file's base name (extension removed).
QTY_RE = re.compile(r"_x(\d+)$")


def quantity_for(stem):
    """Return the quantity encoded in a file's base name (default 1)."""
    m = QTY_RE.search(stem)
    return int(m.group(1)) if m else 1


def escape(name):
    """Escape spaces so Plater reads the filename as a single token."""
    return name.replace(" ", r"\ ")


def write_conf(path, lines, title):
    with open(path, "w") as fh:
        fh.write(f"# {title}\n")
        fh.write(f"# Generated by gen_plater_conf.py -- {len(lines)} part type(s)\n")
        for line in lines:
            fh.write(line + "\n")


def main():
    p = argparse.ArgumentParser(
        description="Generate Plater config file(s) from a directory of parts."
    )
    p.add_argument("directory", help="Directory containing the part files")
    p.add_argument(
        "-o", "--output", default="plater.conf",
        help="Main config file name, written inside DIRECTORY (default: plater.conf)",
    )
    p.add_argument(
        "-a", "--accent-output", default="accent_parts.conf",
        help="Accent-parts config file name (default: accent_parts.conf)",
    )
    p.add_argument(
        "-e", "--ext", default=".stl",
        help="Only include files with this extension, case-insensitive (default: .stl)",
    )
    args = p.parse_args()

    directory = args.directory
    if not os.path.isdir(directory):
        sys.exit(f"error: not a directory: {directory}")

    ext = args.ext.lower()
    files = sorted(
        f for f in os.listdir(directory)
        if os.path.isfile(os.path.join(directory, f)) and f.lower().endswith(ext)
    )
    if not files:
        sys.exit(f"error: no '{ext}' files found in {directory}")

    main_lines, accent_lines = [], []
    for f in files:
        stem = os.path.splitext(f)[0]
        line = f"{escape(f)} {quantity_for(stem)}"
        (accent_lines if f.startswith("[a]") else main_lines).append(line)

    # Config paths are relative to the conf file, so write into the directory.
    main_path = os.path.join(directory, args.output)
    write_conf(main_path, main_lines, "Plater main parts")
    print(f"wrote {main_path} ({len(main_lines)} part type(s))")

    if accent_lines:
        accent_path = os.path.join(directory, args.accent_output)
        write_conf(accent_path, accent_lines, "Plater accent parts")
        print(f"wrote {accent_path} ({len(accent_lines)} part type(s))")


if __name__ == "__main__":
    main()
